source 'https://rubygems.org'

gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'rspec-support'

gem 'dotenv'
gem 'websocket-client-simple'

gem 'rubocop', require: false
gem 'rubocop-rake', require: false
gem 'rubocop-performance', require: false
gem 'standard', require: false

gem 'aws-sdk-s3'
gem 'nokogiri'

gem 'aws-sdk-dynamodb'
gem 'aws-sdk-eventbridge'
gem 'aws-sdk-ssm'

gem 'aws-sdk-cognitoidentityprovider'
gem 'aws-cognito-srp'
gem 'jwt'

gem 'aws-sdk-cloudwatchlogs'
