source 'https://rubygems.org'

group :development do
  gem 'aws-sdk-dynamodb'
  gem 'aws-sdk-s3'
  gem 'rake'
  gem 'dotenv'
  gem 'nokogiri'
end

group :test do
  gem 'minitest', '~> 5.8'
  gem 'minitest-rg', '~> 5.2'
  gem 'minitest-hooks', '~> 1.5'
  gem 'minitest-reporters', '~> 1.1'
  gem "mocha"
end

gem 'dynamoid'