source 'https://rubygems.org'

group :development do
  gem 'aws-sdk-dynamodb'
  gem 'aws-sdk-s3'
  gem 'rake'
  gem 'dotenv'
  gem 'nokogiri'
end

group :test do
  gem "minitest"
  gem "minitest-reporters"
  gem "mocha"
end

gem 'dynamoid'