# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dynamoid'

group :test do
  gem 'minitest', '~> 5.8'
  gem 'minitest-hooks', '~> 1.5'
  gem 'minitest-reporters', '~> 1.1'
  gem 'minitest-rg', '~> 5.2'
  gem 'mocha'
end

group :development, :test do
  gem 'aws-sdk-dynamodb'
  gem 'aws-sdk-s3'
  gem 'dotenv'
  gem 'nokogiri'

  gem 'pry', '~> 0.14.1'
  gem 'rake', '~> 13.0'
  gem 'rubocop', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-performance', require: false
  gem 'standard', require: false
end
