


source 'https://rubygems.org'

gem 'activefunction', '~> 0.4.2'

group :development do
  gem 'aws-sdk-dynamodb'
  gem 'aws-sdk-eventbridge'
  gem 'nokogiri'
end

group :test do 
  gem "minitest"
  gem "mocha"
end 
